! f2py -c -m write_to_file write_to_file.f90
SUBROUTINE WRITE_TO_FILE(XBINNAME, PDATA, KSTEP, KNBZONES)

IMPLICIT NONE

CHARACTER(LEN=256), INTENT(IN)              :: XBINNAME
REAL, DIMENSION(KSTEP, KNBZONES), INTENT(IN) :: PDATA
INTEGER, INTENT(IN)                         :: KSTEP
INTEGER, INTENT(IN)                         :: KNBZONES

INTEGER :: I

OPEN(10, FILE=TRIM(XBINNAME), ACCESS='DIRECT', &
    FORM='UNFORMATTED', STATUS='REPLACE', CONVERT='BIG_ENDIAN', &
    RECL=KNBZONES*4)

DO I=1, KSTEP
    WRITE(10, REC=I) PDATA(I, :)
ENDDO
CLOSE(10)

END SUBROUTINE WRITE_TO_FILE